# -*- coding: utf-8 -*-
"""Base de datos limpia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mFTnPGbmLy1jBdNDz7kn8nuC6Mcj57v
"""



"""# **Este es mi csv con la base de datos limpia**

"""

import pandas as pd
df = pd.read_csv('/content/Datos Gráfica - Datos limpios.csv')
df.head()