# -*- coding: utf-8 -*-
"""datos limpios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dBAH91tp-caXWIDbXHtXLd8xmk3Is_p
"""

import pandas as pd

df = pd.read_csv('/content/sample_data/Estadística General Penitenciaria - DATOS AGOSTO 2024 RM.csv')

df.head()

import pandas as pd

df = pd.read_csv('/content/Estadística General Penitenciaria - DATOS REGIONES AGOSTO 2024.csv')

df.head()

import pandas as pd

df = pd.read_csv('/content/Estadística General Penitenciaria - DATOS REGIONES AGOSTOS 2023.csv')

df.head()

import pandas as pd

df = pd.read_csv('/content/Estadística General Penitenciaria - DATOS REGIONES AGOSTOS 2023.csv')

df.head()